// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsVDwngncLhm54pTNDgc8PP1ZtLS1WBxc',
    appId: '1:170634756914:web:39f50082fbfa9aef4a8d2b',
    messagingSenderId: '170634756914',
    projectId: 'guidely-90d79',
    authDomain: 'guidely-90d79.firebaseapp.com',
    storageBucket: 'guidely-90d79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJcf208GdLO2UF906dteHt8vLOjUUyoHU',
    appId: '1:170634756914:android:34d4281bfe3495664a8d2b',
    messagingSenderId: '170634756914',
    projectId: 'guidely-90d79',
    storageBucket: 'guidely-90d79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxRPIbMcktgEaCmTMeN4rfYkWteugiRpA',
    appId: '1:170634756914:ios:ca4aef757ac1c2274a8d2b',
    messagingSenderId: '170634756914',
    projectId: 'guidely-90d79',
    storageBucket: 'guidely-90d79.appspot.com',
    iosBundleId: 'com.example.guidely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxRPIbMcktgEaCmTMeN4rfYkWteugiRpA',
    appId: '1:170634756914:ios:ca4aef757ac1c2274a8d2b',
    messagingSenderId: '170634756914',
    projectId: 'guidely-90d79',
    storageBucket: 'guidely-90d79.appspot.com',
    iosBundleId: 'com.example.guidely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsVDwngncLhm54pTNDgc8PP1ZtLS1WBxc',
    appId: '1:170634756914:web:3ef6fb57ccb397534a8d2b',
    messagingSenderId: '170634756914',
    projectId: 'guidely-90d79',
    authDomain: 'guidely-90d79.firebaseapp.com',
    storageBucket: 'guidely-90d79.appspot.com',
  );
}